#pragma once
#include "Version.h"

const int STEPPER_DIRECTION_PIN = 32;
const int STEPPER_STEP_PIN = 33;
const int STEPPER_ENABLE_PIN = 14;
#define PIN_STEPPER_MS1        27
#define PIN_STEPPER_MS2        26

const int GREEN_LED = 19;
const int BLUE_LED = 18;
const int RELAY_PIN = 15;

const int STEPPER_MICRO_STEPS = 8;
const int STEPPER_MAX_SPEED = 2500;
const int STEPPER_MAX_ACCELERATION = 5000;
const int STEPPER_MAX_CURRENT = 750;

#define STEPPER_SPR 200
#define WORMGEAR_RATIO 40
#define STEPPER_STEPS_PER_DEGREE (STEPPER_SPR*STEPPER_MICRO_STEPS*WORMGEAR_RATIO/360.0)
#define STEPPER_STEPS_FOR_100_DEGREES (STEPPER_STEPS_PER_DEGREE * 100)

